language: node_js
node_js:
- 10.13.0

branches:
  only:
  - master
#  - develop

script:
- npm rebuild node-sass
- npm run lint
- npm run build:prerender

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  project: saso-text
  skip_cleanup: true
  on:
    branch: master
#      tags: true


# 배포 결과를 이메일로 알린다.
notifications:
  email:
    - ghe.lee19@gmail.com
